from django.urls import path
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('createUser', views.createUser.as_view()),
    path('getUser', views.getUser.as_view()),
    path('InsertFood', views.InsertFood.as_view()),
    path('InsertCars', views.InsertCars.as_view()),
    path('InsertDrug', views.InsertDrug.as_view()),
    path('InsertGoods', views.InsertGoods.as_view()),
    path('InsertUserGoods', views.InsertUserGoods.as_view()),
    path('InsertUserFood', views.InsertUserFood.as_view()),
    path('InsertUserDrugs', views.InsertUserDrugs.as_view()),
    path('InsertUserCars', views.InsertUserCars.as_view()),
    path('GetGoods', views.GetGoods.as_view()),
    path('GetCars', views.GetCars.as_view()),
    path('GetFood', views.GetFood.as_view()),
    path('GetAllFood', views.GetAllFood.as_view()),
    path('GetDrugs', views.GetDrugs.as_view()),
    path('GetAllDrugs', views.GetAllDrugs.as_view()),
    path('GetAllCars', views.GetAllCars.as_view()),
    path('GetAllGoods', views.GetAllGoods.as_view()),
    path('SearchGoods', views.SearchGoods.as_view()),
    path('SearchCars', views.SearchCars.as_view()),
    path('GetGoodsByUPC', views.GetGoodsByUPC.as_view()),
    path('GetDrugsByNDC', views.GetDrugsByNDC.as_view()),
    path('GetFoodByUPC', views.GetFoodByUPC.as_view()),
    path('InsertGoodsIssue', views.InsertGoodsIssue.as_view()),
    path('GetAllGoodsIssues', views.GetAllGoodsIssues.as_view()),
    path('InsertFoodIssue', views.InsertFoodIssue.as_view()),
    path('GetAllFoodIssues', views.GetAllFoodIssues.as_view()),
    path('InsertDrugIssue', views.InsertDrugIssue.as_view()),
    path('GetAllDrugIssues', views.GetAllDrugIssues.as_view()),
    path('InsertCarIssue', views.InsertCarIssue.as_view()),
    path('GetAllCarsIssues', views.GetAllCarsIssues.as_view()),
    path('addGoodsComment', views.addGoodsComment.as_view()),
    path('upVoteGoods', views.upVoteGoods.as_view()),
    path('downVoteGoods', views.downVoteGoods.as_view()),
    path('addFoodComment', views.addFoodComment.as_view()),
    path('upVoteFood', views.upVoteFood.as_view()),
    path('downVoteFood', views.downVoteFood.as_view()),
    path('addCarComment', views.addCarComment.as_view()),
    path('upVoteCar', views.upVoteCar.as_view()),
    path('downVoteCar', views.downVoteCar.as_view()),
    path('addDrugComment', views.addDrugComment.as_view()),
    path('upVoteDrug', views.upVoteDrug.as_view()),
    path('downVoteDrug', views.downVoteDrug.as_view()),
    path('GetCarImage', views.GetCarImage.as_view()),
    path('GetFoodImage', views.GetFoodImage.as_view()),
    path('altProducts', views.altProducts.as_view()),
    path('refreshSaved', views.refreshSaved.as_view()),
    path('InsertreportProduct', views.InsertReportProduct.as_view()),
    path('GetreportProduct', views.GetAllReportProduct.as_view()),
    path('Address', views.AddressView.as_view()),
    path('InsertUserFoodProduct', views.InsertUserFoodProduct.as_view()),
    path('GetUserFoodProduct', views.GetUserFoodProduct.as_view())
    #path('SendEmail', views.sendReportEmail, name ='email')
    #path('email', views.sendReportEmail)
]
