# Generated by Django 2.2 on 2019-04-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallsCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmy', models.CharField(max_length=255, null=True)),
                ('recall', models.CharField(max_length=40000, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallsDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('UPC', models.CharField(max_length=255, null=True)),
                ('recall', models.CharField(max_length=40000, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallsGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('UPC', models.CharField(max_length=255, null=True)),
                ('recall', models.CharField(max_length=40000, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='UPC',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='recall',
            field=models.CharField(max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='recalls_cars',
            field=models.ManyToManyField(to='general.RecallsCars'),
        ),
        migrations.AddField(
            model_name='users',
            name='recalls_drugs',
            field=models.ManyToManyField(to='general.RecallsDrugs'),
        ),
        migrations.AddField(
            model_name='users',
            name='recalls_goods',
            field=models.ManyToManyField(to='general.RecallsGoods'),
        ),
    ]
