# Generated by Django 2.2 on 2019-04-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20190409_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recallsgoods',
            name='UPC',
        ),
        migrations.RemoveField(
            model_name='recallsgoods',
            name='recall',
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='consumerContact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='distributors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='hazards',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='inguries',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='manufacturerCountries',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='manufacturers',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='recallDate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='recallNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='remedies',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='retailers',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsgoods',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recallsgoods',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
