# Generated by Django 2.2 on 2019-04-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20190412_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRecallInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
                ('NHTSAcampaignnumber', models.CharField(max_length=255, null=True)),
                ('reportReceivedDate', models.CharField(max_length=255, null=True)),
                ('Summary', models.CharField(max_length=1000, null=True)),
                ('Conequence', models.CharField(max_length=1000, null=True)),
                ('Remedy', models.CharField(max_length=100, null=True)),
                ('Component', models.CharField(max_length=255, null=True)),
                ('Notes', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recallscars',
            name='mmy',
        ),
        migrations.RemoveField(
            model_name='recallscars',
            name='recall',
        ),
        migrations.RemoveField(
            model_name='recallsdrugs',
            name='UPC',
        ),
        migrations.RemoveField(
            model_name='recallsdrugs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recallsdrugs',
            name='recall',
        ),
        migrations.RemoveField(
            model_name='recallsfood',
            name='UPC',
        ),
        migrations.RemoveField(
            model_name='recallsfood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recallsfood',
            name='recall',
        ),
        migrations.AddField(
            model_name='recallscars',
            name='make',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallscars',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallscars',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='Consequence',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='DrugName',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='DrugType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='NDCs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='ProductDescription',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='RecallCity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='RecallInitiationDate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='RecallNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='RecallReason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='RecallState',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsdrugs',
            name='RecallZip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Product_Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Product_Name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Product_Type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Recall_City',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Recall_Distribution',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Recall_Init_Date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Recall_Number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Recall_Reason',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Recall_State',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='Recall_Zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallsfood',
            name='UPCs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recallsgoods',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recallscars',
            name='recallInfo',
            field=models.ManyToManyField(to='general.CarRecallInfo'),
        ),
    ]
