# Generated by Django 2.2 on 2019-04-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20190414_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recallsdrugs',
            name='DrugName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recallsdrugs',
            name='RecallNumber',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recallsfood',
            name='Product_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recallsfood',
            name='Recall_Number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recallsgoods',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recallsgoods',
            name='recallNumber',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
