# Generated by Django 2.2 on 2019-04-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20190417_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('userID', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carissues',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drugissues',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodissues',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsissues',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carissues',
            name='car_comment',
            field=models.ManyToManyField(to='general.Threads'),
        ),
        migrations.AddField(
            model_name='drugissues',
            name='drug_comment',
            field=models.ManyToManyField(to='general.Threads'),
        ),
        migrations.AddField(
            model_name='foodissues',
            name='food_comment',
            field=models.ManyToManyField(to='general.Threads'),
        ),
        migrations.AddField(
            model_name='goodsissues',
            name='goods_comment',
            field=models.ManyToManyField(to='general.Threads'),
        ),
    ]
