# Generated by Django 2.2 on 2019-04-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20190423_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads',
            name='userID',
        ),
        migrations.AddField(
            model_name='carissues',
            name='userID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='drugissues',
            name='userID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='foodissues',
            name='userID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='goodsissues',
            name='userID',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
