# Generated by Django 2.2 on 2019-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20190423_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carissues',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='drugissues',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='foodissues',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='goodsissues',
            name='userID',
        ),
        migrations.AddField(
            model_name='carissues',
            name='userIDs',
            field=models.ManyToManyField(to='general.UserVotes'),
        ),
        migrations.AddField(
            model_name='drugissues',
            name='userIDs',
            field=models.ManyToManyField(to='general.UserVotes'),
        ),
        migrations.AddField(
            model_name='foodissues',
            name='userIDs',
            field=models.ManyToManyField(to='general.UserVotes'),
        ),
        migrations.AddField(
            model_name='goodsissues',
            name='userIDs',
            field=models.ManyToManyField(to='general.UserVotes'),
        ),
    ]
