# Generated by Django 2.2 on 2019-04-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20190424_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carissues',
            name='userIDs',
        ),
        migrations.RemoveField(
            model_name='drugissues',
            name='userIDs',
        ),
        migrations.RemoveField(
            model_name='foodissues',
            name='userIDs',
        ),
        migrations.RemoveField(
            model_name='goodsissues',
            name='userIDs',
        ),
        migrations.AddField(
            model_name='users',
            name='votes_food',
            field=models.ManyToManyField(related_name='food_votes', to='general.FoodIssues'),
        ),
        migrations.AddField(
            model_name='users',
            name='votes_goods',
            field=models.ManyToManyField(related_name='goods_votes', to='general.GoodsIssues'),
        ),
        migrations.AlterField(
            model_name='users',
            name='issues_food',
            field=models.ManyToManyField(related_name='food_issue', to='general.FoodIssues'),
        ),
        migrations.AlterField(
            model_name='users',
            name='issues_goods',
            field=models.ManyToManyField(related_name='goods_issue', to='general.GoodsIssues'),
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
