# Generated by Django 2.2 on 2019-04-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20190425_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='votes_car',
            field=models.ManyToManyField(related_name='car_votes', to='general.CarIssues'),
        ),
        migrations.AddField(
            model_name='users',
            name='votes_drug',
            field=models.ManyToManyField(related_name='drug_votes', to='general.DrugIssues'),
        ),
        migrations.AlterField(
            model_name='users',
            name='issues_cars',
            field=models.ManyToManyField(related_name='car_issue', to='general.CarIssues'),
        ),
        migrations.AlterField(
            model_name='users',
            name='issues_drugs',
            field=models.ManyToManyField(related_name='drug_issue', to='general.DrugIssues'),
        ),
    ]
