# Generated by Django 2.2 on 2019-04-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_carimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimages',
            name='url',
        ),
        migrations.AddField(
            model_name='carimages',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
