# Generated by Django 2.2 on 2019-04-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20190429_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
