# Generated by Django 2.2 on 2019-04-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20190429_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
