# Generated by Django 3.0.3 on 2020-05-04 02:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_foodimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('street1', models.CharField(max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hasserialnumber', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectProductCategory', models.CharField(choices=[('Goods', 'Goods'), ('Car', 'Car'), ('Drug', 'Drug'), ('Food', 'Food')], default='Goods', max_length=30, null=True)),
                ('identifyProduct', models.CharField(max_length=255)),
                ('upc', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('useremail', models.CharField(max_length=255)),
                ('userZipCode', models.CharField(max_length=255, null=True)),
                ('userPhoneNumber', models.CharField(max_length=255)),
                ('preferredcontactmethod', models.CharField(choices=[('Email', 'Email'), ('PhoneNumber', 'PhoneNumber')], default='PhoneNumber', max_length=25, null=True)),
                ('locationOfPurchase', models.CharField(max_length=255, null=True)),
                ('medicalCare', models.BooleanField(default=False, null=True)),
                ('doctorName', models.CharField(blank=True, default='null', max_length=255)),
                ('describeProblem', models.TextField(blank=True, null=True)),
                ('agreeToStatement', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='agreeToTerms',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(max_length=255)),
                ('unspsc', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('error', 'error')], default='pending', max_length=10)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('mfrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Manufacturer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Users')),
                ('userAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Users'),
        ),
    ]
