# Generated by Django 2.2 on 2020-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20200504_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default='test@testingtest.com', max_length=255),
            preserve_default=False,
        ),
    ]
