# Generated by Django 2.2 on 2022-12-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_address_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_products_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifter_id', models.CharField(max_length=20)),
                ('fda_id', models.CharField(blank=True, max_length=20)),
                ('users_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='general.Users')),
            ],
        ),
    ]
