# Generated by Django 2.2 on 2022-12-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_user_products_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_products_food',
            old_name='users_id',
            new_name='users',
        ),
    ]
