# Generated by Django 2.2 on 2022-12-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_auto_20221208_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_products_food',
            new_name='Users_products_food',
        ),
    ]
