# Generated by Django 2.2 on 2022-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20221208_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_products_food',
            name='productName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
